version: '3.8'

services:
  rabbitmq:
    env_file: .env
    container_name: ${RABBITMQ_SERVER_NAME}
    build:
      context: ./rabbitmq
      dockerfile: DockerFile
    volumes:
      - ./meter/log/:/app/log/
    hostname: local
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
  meter:
    env_file: .env
    build:
      context: ./meter
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
  pv_simulator:
    env_file: .env
    build:
      context: ./pvsimulator
      dockerfile: Dockerfile
    volumes:
      - ./pvsimulator/log/:/app/log/
    depends_on:
      - "rabbitmq"
      - "meter"
      