version: '3.8'

services:
  rabbitmq:
    env_file: .env
    container_name: ${RABBITMQ_SERVER_NAME}
    build:
      context: ./rabbitmq
      dockerfile: DockerFile
    hostname: local
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
  meter:
    env_file: .env
    build:
      context: ./meter
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
